feat: implement the main page
mishashmidt0/who-am-I pull request #3
Opened 2023-01-31 17:34 UTC by Ananasovna

2023-01-31 18:59 UTC, mishashmidt0 requested changes

2023-01-31 18:59 UTC, mishashmidt0 commented on src/pages/index.tsx
> +        {BUTTON_ARR.map(button => <button key={button.id}
переменуй плиз button в el 
иначе непонятно, везде buttonы какое то

2023-01-31 18:59 UTC, mishashmidt0 commented on src/pages/index.tsx
> +        </button>)}
Еще создай кнопку button отдельным компонентом, в которую через пропсы можно прокидывать title 
что бы эту кнопку в дальнейшем мы смогли везде использовать

2023-01-31 18:59 UTC, mishashmidt0 commented on src/pages/index.tsx
> +    bg-[url('../../public/image/img/bgMain.png')]" >
посмотри как в конфиг tailwind можно добавлять картинку

2023-02-01 10:09 UTC, Ananasovna commented on src/pages/index.tsx
> +        {BUTTON_ARR.map(button => <button key={button.id}
сделано

2023-02-01 10:09 UTC, Ananasovna commented on src/pages/index.tsx
> +    bg-[url('../../public/image/img/bgMain.png')]" >
сделано

2023-02-01 11:03 UTC, Ananasovna commented on src/pages/index.tsx
> +        </button>)}
сделано

2023-02-01 11:33 UTC, mishashmidt0 approved these changes

2023-02-01 15:35 UTC, merged